// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa0jDvCzgoifsU8wBo5AB7KqMw5p6q-Wg',
    appId: '1:502132402573:android:2d1c8ef1ea46a8189975c4',
    messagingSenderId: '502132402573',
    projectId: 'lastsub-40667',
    storageBucket: 'lastsub-40667.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiFitmW0M2uHJQsz75VE_BCux6EodbAhM',
    appId: '1:502132402573:ios:b6d80a99142469a29975c4',
    messagingSenderId: '502132402573',
    projectId: 'lastsub-40667',
    storageBucket: 'lastsub-40667.firebasestorage.app',
    androidClientId: '502132402573-qe0f5istjumvpbc2k2ljjt5h008vusqb.apps.googleusercontent.com',
    iosClientId: '502132402573-40uucevilrdfinb546eo9mh7j0jaqtfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.smopFinal',
  );

}